//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicornShopLegacy
{
    using System;
    using System.Collections.Generic;

#pragma warning disable CS8981 // Type name only contains lower-cased ascii characters
    public partial class inventory
#pragma warning restore CS8981
    {
        public System.Guid unicorn_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<decimal> price { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
    }
}
