//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicornShopLegacy
{
    using System;
    using System.Collections.Generic;

#pragma warning disable CS8981 // Type name only contains lower-cased ascii characters
    public partial class user
#pragma warning restore CS8981
    {
        public System.Guid user_id { get; set; }
        public string email { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string password { get; set; }
    }
}
